<a href="https://colab.research.google.com/github/Bikas0/Pytorch/blob/main/PytorchPart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'1.10.0+cu111'

In [ ]:
import numpy as np

list = [1, 2 , 3, 4]
list

[1, 2, 3, 4]

In [ ]:
np_arr = np.array(list)
np_arr

array([1, 2, 3, 4])

In [ ]:
np_arr.dtype

dtype('int64')

In [ ]:
 
#Convert numpy to array
tensor = torch.from_numpy(np_arr)
tensor

tensor([1, 2, 3, 4])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor[2]

tensor(3)

In [ ]:
tensor[0:3]

tensor([1, 2, 3])

In [ ]:
tensor[:]

tensor([1, 2, 3, 4])

In [ ]:
tensor[2] = 100

**from_numpy() have a problem ,Tensor and array use the same memory location**
## If change any value in tensor then also change np_arr value

In [ ]:
tensor

tensor([  1,   2, 100,   4])

In [ ]:
np_arr

array([  1,   2, 100,   4])

In [ ]:
#prevent the from_numpy() problem use tensor

In [ ]:
torch1 = torch.tensor(np_arr)

In [ ]:
torch1

tensor([  1,   2, 100,   4])

In [ ]:
torch1[1] = 5
torch1

tensor([  1,   5, 100,   4])

In [ ]:
np_arr

array([  1,   2, 100,   4])

In [ ]:
x = torch.ones(2,3, dtype = torch.int32)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
y = torch.tensor([2,8,5,4], dtype = torch.int32)
d = torch.tensor([9,1,3,7], dtype = torch.int32)

In [ ]:
print(y+d)

tensor([11,  9,  8, 11], dtype=torch.int32)


In [ ]:
torch.add(y,d)

tensor([11,  9,  8, 11], dtype=torch.int32)

In [ ]:
torch.add(y,d).sum()

tensor(39)

In [ ]:
torch.mul(y,d)

tensor([18,  8, 15, 28], dtype=torch.int32)

In [ ]:
torch.dot(y,d)

tensor(69, dtype=torch.int32)

In [ ]:
## Matrix multiplication

In [ ]:
x = torch.tensor([[1,2], [5,7]],dtype = torch.int32)
y = torch.tensor([[0,4,4,7,9], [5,7,0,14,1]],dtype = torch.int32)

In [ ]:
torch.mm(x,y)

tensor([[ 10,  18,   4,  35,  11],
        [ 35,  69,  20, 133,  52]], dtype=torch.int32)

In [ ]:
torch.matmul(x,y)

tensor([[ 10,  18,   4,  35,  11],
        [ 35,  69,  20, 133,  52]], dtype=torch.int32)

# **Backward propagation of y = x^3**

In [ ]:
x = torch.tensor(4, requires_grad= True, dtype = torch.float32) # requires_grad True because we want 
## to calculate backpropagation which determine by gradient. 
## if you use requires_grad = False that time you can not determine gradient.

In [ ]:
y = x**3
y

tensor(64., grad_fn=<PowBackward0>)

In [ ]:
print(x.grad)

None


In [ ]:
y.backward()

In [ ]:
print(x.grad)

tensor(48.)
